# This workflow will build a Java project with Maven and bundle them as native app installers with jDeploy

name: Build Releases

on:
  push:
    branches: ['*', '!gh-pages']
    tags: ['*']
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      commit-hash-exists: ${{ steps.check-commit-hash.outputs.commit-hash-exists }}
      secrets-defined: ${{ steps.check-secrets.outputs.secrets-defined }}
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Check if commit hash file exists
        id: check_file
        run: |
          if [ -f "commit_hash.txt" ]; then
            echo "COMMIT_HASH_EXISTS=true" >> $GITHUB_ENV
          else
            echo "COMMIT_HASH_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Clone repo
        if: env.COMMIT_HASH_EXISTS == 'true'
        run: |
          git clone https://github.com/argouml-tigris-org/argouml --depth=1
          cd argouml

      - name: Build with Maven
        if: env.COMMIT_HASH_EXISTS == 'true'
        run: |
          cd argouml
          mvn package -DskipTests
          mkdir ../build
          mv src/argouml-build/target/argouml-jar-with-dependencies.jar ../build/argouml-jar-with-dependencies.jar

      - name: Build App Installer Bundles
        if: env.COMMIT_HASH_EXISTS == 'true'
        uses: shannah/jdeploy@self-sign-mac
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine if sign-and-notarize should run
        if: env.COMMIT_HASH_EXISTS == 'true'
        id: check-commit-hash
        run: |
          echo "::set-output name=commit-hash-exists::true"

      - name: Check if secrets are defined
        if: env.COMMIT_HASH_EXISTS == 'true'
        id: check-secrets
        run: |
          if [ -n "${{ secrets.MAC_DEVELOPER_CERTIFICATE }}" ] && [ -n "${{ secrets.APPLE_ID }}" && [ -n "${{ secrets.MAC_DEVELOPER_CERTIFICATE_PASSWORD }}" ]; then
            echo "Secrets are defined."
            echo "::set-output name=secrets-defined::true"
          else
            echo "Secrets are not defined."
            echo "::set-output name=secrets-defined::false"
          fi

  sign-and-notarize:
    permissions:
      contents: write
    runs-on: macos-latest
    needs: build
    if: ${{ needs.build.outputs.commit-hash-exists == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Sign and Notarize macOS Apps Action
        uses: shannah/jdeploy/codesign-mac@self-sign-mac
        with:
          signing_certificate: ${{ secrets.MAC_DEVELOPER_CERTIFICATE }}
          signing_certificate_password: ${{ secrets.MAC_DEVELOPER_CERTIFICATE_PASSWORD }}
          apple_id: ${{ secrets.MAC_DEVELOPER_APPLE_ID }}
          notarization_key_id: ${{ secrets.NOTARIZATION_KEY_ID }}
          notarization_issuer_id: ${{ secrets.NOTARIZATION_KEY_ISSUER_ID }}
          notarization_api_key_base64: ${{ secrets.NOTARIZATION_KEY_P8 }}
